org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

#read more on this at https://github.com/neoforged/NeoGradle/blob/NG_7.0/README.md#apply-parchment-mappings
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.4
parchment_mappings_version=2024.12.29


minecraft_version=1.21.4
minecraft_version_range=[1.21.4, 1.22)

neo_version=21.4.47-beta
neo_version_range=[21.4.0-beta,)
loader_version_range=[4,)

## Mod Properties
mod_name=Player Ladder
mod_id=playerladder
mod_version=0.7.2-beta
mod_license=MIT

mod_group_id=ru.nern.playerladder
mod_authors=ForwarD NerN
mod_description=Adds the ability to ride/pick up other players on a head by right-clicking on them.
