# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.1
loom_version=1.13-SNAPSHOT

# Mod Properties
mod_version=0.7.4
maven_group=ru.nern
archives_base_name=playerladder

# Dependencies
fabric_version=0.138.3+1.21.10
cloth_config_version=20.0.149
modmenu_version=16.0.0-rc.1
fconfig_version=1.1.1